/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class CameraUI extends View {
		public posX:Laya.HSlider;
		public rotationY:Laya.HSlider;
		public rotationX:Laya.HSlider;
		public posY:Laya.HSlider;
		public posZ:Laya.HSlider;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadUI("Camera");
        }
    }
    REG("ui.CameraUI",CameraUI);
    export class HudUI extends View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadUI("Hud");
        }
    }
    REG("ui.HudUI",HudUI);
}
